CREATE DATABASE biblioteca;
use biblioteca;

CREATE TABLE BIBLIOTECA_ESTADO_TB(
ID_ESTADO INT PRIMARY KEY AUTO_INCREMENT,
DESCRIPCION VARCHAR(100) NOT NULL);




CREATE TABLE BIBLIOTECA_ROLE_TB(
ID_ROLE INT PRIMARY KEY AUTO_INCREMENT, 
DESCRIPCION VARCHAR(100) NOT NULL,
ID_ESTADO INT NOT NULL, 
FOREIGN KEY (ID_ESTADO) REFERENCES BIBLIOTECA_ESTADO_TB(ID_ESTADO));

CREATE TABLE BIBLIOTECA_USUARIOS_TB(
ID_USUARIO INT auto_increment PRIMARY KEY AUTO_INCREMENT, 
NOMBRE VARCHAR(100) NOT NULL, 
EMAIL VARCHAR(100) UNIQUE NOT NULL,
CODIGO_POSTAL bigint NULL, 
TELEFONO bigint NOT NULL, 
CEDULA bigint UNIQUE, 
CONTRA VARCHAR(20),
ID_ROLE INT  NOT NULL,
ID_ESTADO INT NOT NULL,
FOREIGN KEY (ID_ROLE) REFERENCES BIBLIOTECA_ROLE_TB (ID_ROLE),
FOREIGN KEY (ID_ESTADO) REFERENCES BIBLIOTECA_ESTADO_TB (ID_ESTADO));


CREATE TABLE BIBLIOTECA_AUTOR_TB(
ID_AUTOR INT PRIMARY KEY AUTO_INCREMENT, 
NOMBRE VARCHAR(100) NOT NULL, 
ID_ESTADO INT NOT NULL,
FOREIGN KEY (ID_ESTADO) REFERENCES BIBLIOTECA_ESTADO_TB (ID_ESTADO));

CREATE TABLE BIBLIOTECA_GENERO_TB (
ID_GENERO INT PRIMARY KEY AUTO_INCREMENT, 
NOMBRE VARCHAR(100) NOT NULL, 
ID_ESTADO INT NOT NULL,
FOREIGN KEY (ID_ESTADO) REFERENCES BIBLIOTECA_ESTADO_TB (ID_ESTADO));


CREATE TABLE BIBLIOTECA_CATEGORIA_TB(
ID_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT, 
NOMBRE VARCHAR(100) NOT NULL, 
ID_ESTADO INT NOT NULL,
FOREIGN KEY (ID_ESTADO) REFERENCES BIBLIOTECA_ESTADO_TB (ID_ESTADO));


CREATE TABLE BIBLIOTECA_PRODUCTOS_TB(
ID_PRODUCTOS INT PRIMARY KEY AUTO_INCREMENT, 
NOMBRE VARCHAR(100) NOT NULL, 
ID_CATEGORIA INT NOT NULL,
ID_ESTADO INT NOT NULL,
FOREIGN KEY (ID_CATEGORIA) REFERENCES BIBLIOTECA_CATEGORIA_TB (ID_CATEGORIA),
FOREIGN KEY (ID_ESTADO) REFERENCES BIBLIOTECA_ESTADO_TB (ID_ESTADO));


CREATE TABLE BIBLIOTECA_METODO_PAGO_TB(
ID_METODO INT PRIMARY KEY NOT NULL AUTO_INCREMENT, 
METODO_PAGO varchar(20) NOT NULL, 
ENTIDAD_BANCARIA varchar(20) NOT NULL, 
N_TARJETA BIGINT NOT NULL; 
ID_ESTADO INT NOT NULL, 
FOREIGN KEY (ID_ESTADO) REFERENCES BIBLIOTECA_ESTADO_TB(ID_ESTADO));

CREATE TABLE BIBLIOTECA_RESEÑA_TB(
ID_REVIEW INT PRIMARY KEY AUTO_INCREMENT, 
REVIEW VARCHAR(100) NOT NULL, 
ID_ESTADO INT NOT NULL,
ID_USUARIO INT NOT NULL, 
FOREIGN KEY (ID_USUARIO) REFERENCES BIBLIOTECA_USUARIOS_TB (ID_USUARIO),
FOREIGN KEY (ID_ESTADO) REFERENCES BIBLIOTECA_ESTADO_TB (ID_ESTADO));


CREATE TABLE BIBLIOTECA_LIBROS_TB(
  ID_LIBROS INT PRIMARY KEY NOT NULL AUTO_INCREMENT, 
  STOCK INT NOT NULL, 
  PRECIO_ALQUILER DECIMAL, 
  ID_AUTOR INT NOT NULL,
  ID_GENERO INT NOT NULL,
  ID_REVIEW INT NOT NULL,
  ID_ESTADO INT NOT NULL,
  FOREIGN KEY (ID_AUTOR) REFERENCES BIBLIOTECA_AUTOR_TB (ID_AUTOR),
  FOREIGN KEY (ID_GENERO) REFERENCES BIBLIOTECA_GENERO_TB (ID_GENERO),
  FOREIGN KEY (ID_REVIEW) REFERENCES BIBLIOTECA_RESEÑA_TB (ID_REVIEW),
  FOREIGN KEY (ID_ESTADO) REFERENCES BIBLIOTECA_ESTADO_TB (ID_ESTADO)
);

CREATE TABLE BIBLIOTECA_RECLAMOS_TB(
  ID_RECLAMOS INT PRIMARY KEY NOT NULL AUTO_INCREMENT, 
  DESCRIPCION VARCHAR(100),
  ID_LIBRO INT NOT NULL, 
  ID_USUARIO INT NOT NULL, 
  ID_ESTADO INT NOT NULL,
  FOREIGN KEY (ID_LIBRO) REFERENCES BIBLIOTECA_LIBROS_TB (ID_LIBROS),
  FOREIGN KEY (ID_USUARIO) REFERENCES BIBLIOTECA_USUARIOS_TB (ID_USUARIO),
  FOREIGN KEY (ID_ESTADO) REFERENCES BIBLIOTECA_ESTADO_TB (ID_ESTADO)
);

CREATE TABLE BIBLIOTECA_RESERVAS_TB(
ID_RESERVAS INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
ID_LIBRO INT NOT NULL,
ID_USUARIO INT NOT NULL,
FECHA DATETIME,
ID_ESTADO INT NOT NULL,
FOREIGN KEY (ID_LIBRO) REFERENCES BIBLIOTECA_LIBROS_TB (ID_LIBROS),
FOREIGN KEY (ID_USUARIO) REFERENCES BIBLIOTECA_USUARIOS_TB (ID_USUARIO),
FOREIGN KEY (ID_ESTADO) REFERENCES BIBLIOTECA_ESTADO_TB (ID_ESTADO)
);



CREATE TABLE BIBLIOTECA_FACTURAS_TB(
  ID_FACTURA INT PRIMARY KEY NOT NULL AUTO_INCREMENT, 
  FECHA_FACTURA DATETIME, 
  TOTAL DECIMAL NOT NULL,
  ID_USUARIO INT NOT NULL, 
  ID_METODO INT NOT NULL,
  ID_PRODUCTO INT NOT NULL, 
  ID_RESERVAS INT NOT NULL,
  ID_ESTADO INT NOT NULL,
  FOREIGN KEY (ID_ESTADO) REFERENCES BIBLIOTECA_ESTADO_TB(ID_ESTADO),
  FOREIGN KEY (ID_USUARIO) REFERENCES BIBLIOTECA_USUARIOS_TB (ID_USUARIO),
  FOREIGN KEY (ID_METODO) REFERENCES BIBLIOTECA_METODO_PAGO_TB (ID_METODO),
  FOREIGN KEY (ID_PRODUCTO) REFERENCES BIBLIOTECA_PRODUCTOS_TB (ID_PRODUCTOS),
  FOREIGN KEY (ID_RESERVAS) REFERENCES BIBLIOTECA_RESERVAS_TB (ID_RESERVAS)
);
